import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import crypto from "node:crypto";

const JWT_SECRET = process.env.JWT_SECRET || "online-judge-secret-key-2026";
const SALT_ROUNDS = 10;

export function signToken(payload, expiresIn = "24h") {
  return jwt.sign(payload, JWT_SECRET, { expiresIn });
}

export function verifyToken(token) {
  if (!token || typeof token !== "string") {
    return null;
  }

  try {
    return jwt.verify(token, JWT_SECRET);
  } catch (err) {
    // Fallback for custom HMAC tokens generated by legacy system
    try {
      const parts = token.split(".");
      if (parts.length === 3) {
        const [encodedHeader, encodedPayload, signature] = parts;
        const expectedSignature = crypto
          .createHmac("sha256", JWT_SECRET)
          .update(`${encodedHeader}.${encodedPayload}`)
          .digest("base64url");

        if (signature === expectedSignature) {
          const base64 = encodedPayload.replace(/-/g, "+").replace(/_/g, "/");
          const payload = JSON.parse(Buffer.from(base64, "base64").toString("utf8"));
          const now = Math.floor(Date.now() / 1000);
          if (payload.exp && payload.exp < now) return null;
          return payload;
        }
      }
    } catch (e) {}
    return null;
  }
}

export async function hashPassword(password) {
  if (!password) return "";
  return bcrypt.hash(password, SALT_ROUNDS);
}

export function hashPasswordSync(password) {
  if (!password) return "";
  return bcrypt.hashSync(password, SALT_ROUNDS);
}

export async function verifyPassword(password, hash) {
  if (!password || !hash) return false;
  // Support plain text match (e.g. initial seed records)
  if (password === hash) return true;
  // Backward compatibility: If hash is 64-char hex string (plain SHA256)
  if (hash.length === 64 && /^[a-f0-9]+$/i.test(hash)) {
    const legacyHash = crypto.createHash("sha256").update(password).digest("hex");
    return legacyHash === hash;
  }
  try {
    return await bcrypt.compare(password, hash);
  } catch (e) {
    return false;
  }
}

export function verifyPasswordSync(password, hash) {
  if (!password || !hash) return false;
  if (password === hash) return true;
  if (hash.length === 64 && /^[a-f0-9]+$/i.test(hash)) {
    const legacyHash = crypto.createHash("sha256").update(password).digest("hex");
    return legacyHash === hash;
  }
  try {
    return bcrypt.compareSync(password, hash);
  } catch (e) {
    return false;
  }
}
